---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xsecrets.sec.upbound.io
spec:
  compositeTypeRef:
    apiVersion: sec.upbound.io/v1alpha1
    kind: XSecret
  mode: Pipeline
  pipeline:
    - functionRef:
        name: crossplane-contrib-function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          - base:
              apiVersion: vault.vault.upbound.io/v1alpha1
              kind: Mount
              spec:
                deletionPolicy: Delete
                forProvider:
                  description: Crossplane created secret mount.
                  externalEntropyAccess: false
                  path: kv-v2
                  type: kv-v2
            name: kv-v2-secret-mount
            patches:
              - fromFieldPath: spec.parameters.id
                toFieldPath: metadata.name
                transforms:
                  - string:
                      fmt: '%s-kv-v2-secret-mount'
                      type: Format
                    type: string
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.providerConfigName
                toFieldPath: spec.providerConfigRef.name
                type: FromCompositeFieldPath
              - fromFieldPath: status.atProvider
                policy:
                  fromFieldPath: Required
                toFieldPath: status.kvV2SecretMount
                type: ToCompositeFieldPath
          - base:
              apiVersion: vault.vault.upbound.io/v1alpha1
              kind: Mount
              spec:
                deletionPolicy: Delete
                forProvider:
                  description: Crossplane created secret mount.
                  externalEntropyAccess: false
                  path: transit
                  type: transit
            name: transit-secret-mount
            patches:
              - fromFieldPath: spec.parameters.id
                toFieldPath: metadata.name
                transforms:
                  - string:
                      fmt: '%s-transit-secret-mount'
                      type: Format
                    type: string
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.providerConfigName
                toFieldPath: spec.providerConfigRef.name
                type: FromCompositeFieldPath
              - fromFieldPath: status.atProvider
                policy:
                  fromFieldPath: Required
                toFieldPath: status.transitSecretMount
                type: ToCompositeFieldPath
          - base:
              apiVersion: transit.vault.upbound.io/v1alpha1
              kind: SecretBackendKey
              spec:
                deletionPolicy: Delete
                forProvider:
                  allowPlaintextBackup: false
                  backend: transit
                  convergentEncryption: false
                  deletionAllowed: true
                  derived: false
                  exportable: false
                  minDecryptionVersion: 1
                  minEncryptionVersion: 0
                  type: aes256-gcm96
            name: transit-secret-backend-key
            patches:
              - fromFieldPath: spec.parameters.id
                toFieldPath: metadata.name
                transforms:
                  - string:
                      fmt: '%s-transit-secret-backend-key'
                      type: Format
                    type: string
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.transitKeyName
                toFieldPath: spec.forProvider.name
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.providerConfigName
                toFieldPath: spec.providerConfigRef.name
                type: FromCompositeFieldPath
              - fromFieldPath: status.atProvider
                policy:
                  fromFieldPath: Required
                toFieldPath: status.transitSecretBackendKey
                type: ToCompositeFieldPath
      step: patch-and-transform
